spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb:/USERSERVICE
          predicates:
            - Path=/users/**



        - id: RATINGSERVICE
          uri: lb:/RATINGSERVICE
          predicates:
            - Path=/rating/**


        - id: HOTELSERVICE
          uri: lb:/HOTELSERVICE
          predicates:
            - Path=/hotel/**

